version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis.{domain}
    stdin_open: true
    tty: true
    networks:
      - global
    restart: always

  mysql:
    image: mariadb
    container_name: mysql.{domain}
    stdin_open: true
    tty: true
    networks:
      - global
    env_file:
       - ./docker/mysql/config.env
    volumes:
       - ~/data/mysql.{domain}:/var/lib/mysql
    restart: always

  php:
    image: amsdard.io/{namespace}/php:1.0
    container_name: php.{domain}
    build:
        context: ./
        dockerfile: ./docker/php/Dockerfile
    networks:
      - global
    stdin_open: true
    tty: true
    env_file:
       - ./.env
    volumes:
       - ./:/opt
       - ~/.ssh:/var/www/.ssh:cached
       - ~/.docker-composer:/var/www/.composer:cached
    links:
       - mysql
       - redis
    restart: always

  nginx:
    image: amsdard.io/{namespace}/nginx:1.0
    container_name: nginx.{domain}
    build:
        context: ./
        dockerfile: ./docker/nginx/Dockerfile
    networks:
      - global
    stdin_open: true
    tty: true
    labels:
       traefik.frontend.rule: "Host:{subdomain}.{domain},{domain}"
    volumes:
       - ./web:/opt/web:cached
       - ./docker/nginx/:/etc/nginx/conf.d:cached
    links:
       - php
    restart: always

networks:
  global:
    external: true
